### ISSUE TITLE
Patched Bisect?

### ISSUE THREAD

**Issue by infidel** [sagotch/ocveralls.sh#2]
This is more of a question than an issue, but what is the status of the patched version of Bisect that is required for ocveralls, i.e. do you know when it will be released? Was the patch created by you or by the author of Bisect?

**Comment by sagotch** [comment]
The patch was created by the author of bisect, and he said me that next release could come in a loooooong time.

But I started to work on a standalone program to generate coveralls from non-patched bisect. It should come up in few days since a already have things working for simple cases.

**Comment by infidel** [comment]
Thanks for your reply, looking forward to it.

**Comment by sagotch** [comment]
New https://github.com/sagotch/ocveralls is out now. :+1:
